# Generated by Django 4.2.21 on 2025-05-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommanderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ein eindeutiger Name für diese Regel.', max_length=100, unique=True)),
                ('trigger_phrase', models.TextField(help_text='Die Phrase oder das Muster, das diese Regel auslöst.')),
                ('match_type', models.CharField(choices=[('exact', 'Exakte Übereinstimmung'), ('contains', 'Enthält (Groß-/Kleinschreibung ignorieren)'), ('startswith', 'Beginnt mit (Groß-/Kleinschreibung ignorieren)'), ('regex', 'Regulärer Ausdruck')], default='contains', help_text='Wie die trigger_phrase mit der eingehenden Nachricht abgeglichen werden soll.', max_length=15)),
                ('response_template', models.TextField(help_text='Die Antwortvorlage. Verwenden Sie Platzhalter wie <SENDER_LONG_NAME>, <SENDER_LATITUDE>, <SENDER_LONGITUDE>, <RECEIVED_MESSAGE_TEXT>, etc.')),
                ('enabled', models.BooleanField(default=True, help_text='Ist diese Regel aktiv?')),
                ('cooldown_seconds', models.PositiveIntegerField(default=60, help_text='Minimale Zeit in Sekunden, bevor diese Regel für denselben Absenderknoten erneut ausgelöst wird. 0 für keinen Cooldown.')),
                ('last_triggered_for_nodes', models.JSONField(blank=True, default=dict, help_text='Zeitstempel der letzten Auslösung pro Knoten-ID für Cooldown-Management.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commander Regel',
                'verbose_name_plural': 'Commander Regeln',
                'ordering': ['name'],
            },
        ),
    ]
