# Generated by Django 5.2.5 on 2025-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrastics_commander", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommanderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chatbot_mode_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Wenn aktiviert, werden alle Nachrichten direkt an ChatGPT weitergeleitet.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commander Einstellung",
                "verbose_name_plural": "Commander Einstellungen",
            },
        ),
    ]
