# Generated by Django 4.2.21 on 2025-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrastics_listener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerState',
            fields=[
                ('singleton_id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INITIALIZING', 'Initializing'), ('CONNECTING', 'Connecting'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('local_node_id', models.CharField(blank=True, max_length=24, null=True)),
                ('local_node_num', models.PositiveIntegerField(blank=True, null=True)),
                ('local_node_name', models.CharField(blank=True, max_length=100, null=True)),
                ('local_node_channel_map_json', models.JSONField(blank=True, help_text='JSON representation of the channel map', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Listener State',
                'verbose_name_plural': 'Listener States',
            },
        ),
    ]
